# Base URL setting
@baseUrl = http://localhost:4004

############################################################################
#                            POSITIVE TEST CASES                           #
############################################################################

### ------------------------------------------------------------------------
# Admin retrieves all Spacefarers
GET {{baseUrl}}/odata/v4/spacefarer/GalacticSpacefarers
Authorization: Basic admin@space.com:password

### ------------------------------------------------------------------------
# Junior retrieves all Spacefarers
GET {{baseUrl}}/odata/v4/spacefarer/GalacticSpacefarers
Authorization: Basic junior@space.com:password

### ------------------------------------------------------------------------
# Admin creates a new Spacefarer
POST {{baseUrl}}/odata/v4/spacefarer/GalacticSpacefarers
Authorization: Basic admin@space.com:password
Content-Type: application/json

{
    "name": "Test Spacefarer",
    "email": "test6@spacefarer.com",
    "password": "password",
    "stardustCollection": 5,
    "wormholeNavigationSkill": 3,
    "originPlanet": "Earth",
    "spacesuitColor": "Red",
    "department_ID": "7dacdb28-0601-40f0-8c64-cd86732db1f0",
    "position_ID": "40493cf4-e1af-4ca7-bbc1-941bd80bd97e"
}

### ------------------------------------------------------------------------
# User with SpacefarerUser role PATCHs own stardust collection

PATCH {{baseUrl}}/odata/v4/spacefarer/GalacticSpacefarers(70416e33-224b-4970-a624-168662918af5)
Authorization: Basic junior@space.com:password
Content-Type: application/json

{
    "stardustCollection": 21
}

### ------------------------------------------------------------------------
# User with SpacefarerUser role PATCHs own spacesuit color
PATCH {{baseUrl}}/odata/v4/spacefarer/GalacticSpacefarers(70416e33-224b-4970-a624-168662918af5)
Authorization: Basic junior@space.com:password
Content-Type: application/json

{
    "spacesuitColor": "Gold"
}

### ------------------------------------------------------------------------
# Admin PATCHs any field
PATCH {{baseUrl}}/odata/v4/spacefarer/GalacticSpacefarers(70416e33-224b-4970-a624-168662918af5)
Authorization: Basic admin@space.com:password
Content-Type: application/json

{
    "name": "Patched Junior",
    "wormholeNavigationSkill": 5,
    "stardustCollection": 100
}

############################################################################
#                            NEGATIVE TEST CASES                           #
############################################################################

### ------------------------------------------------------------------------
# Call without authentication (401 Unauthorized)
GET {{baseUrl}}/odata/v4/spacefarer/GalacticSpacefarers

### ------------------------------------------------------------------------
# User with SpacefarerUser role tries to create a Spacefarer (403 Forbidden)
POST {{baseUrl}}/odata/v4/spacefarer/GalacticSpacefarers
Authorization: Basic junior@space.com:password
Content-Type: application/json

{
    "name": "Test Spacefarer",
    "email": "test@spacefarer.com",
    "stardustCollection": 5,
    "wormholeNavigationSkill": 3,
    "originPlanet": "Earth",
    "spacesuitColor": "Red",
    "department_ID": "7dacdb28-0601-40f0-8c64-cd86732db1f0",
    "position_ID": "40493cf4-e1af-4ca7-bbc1-941bd80bd97e"
}

### ------------------------------------------------------------------------
# Using wrong password (401 Unauthorized)
GET {{baseUrl}}/odata/v4/spacefarer/GalacticSpacefarers
Authorization: Basic admin@space.com:wrongpassword

### ------------------------------------------------------------------------
# Non-existent user (401 Unauthorized)
GET {{baseUrl}}/odata/v4/spacefarer/GalacticSpacefarers
Authorization: Basic nonexisting@spacefarer.com:password

### ------------------------------------------------------------------------
# User with SpacefarerUser role tries to delete a Spacefarer (403 Forbidden)

DELETE {{baseUrl}}/odata/v4/spacefarer/GalacticSpacefarers(8116360c-74fa-431c-97a0-60e667c179e9)
Authorization: Basic junior@space.com:password
