# Base URL setting
@baseUrl = http://localhost:4004

### ------------------------------------------------------------------------
# User with SpacefarerUser role tries to PATCH forbidden field
PATCH {{baseUrl}}/odata/v4/spacefarer/GalacticSpacefarers(70416e33-224b-4970-a624-168662918af5)
Authorization: Basic junior@space.com:password
Content-Type: application/json

{
    "name": "New Name Attempt"
}

### ------------------------------------------------------------------------
# User with SpacefarerUser role tries to PATCH multiple fields including forbidden ones
PATCH {{baseUrl}}/odata/v4/spacefarer/GalacticSpacefarers(70416e33-224b-4970-a624-168662918af5)
Authorization: Basic junior@space.com:password
Content-Type: application/json

{
    "stardustCollection": 30,
    "spacesuitColor": "White"
}

### ------------------------------------------------------------------------
# Stardust collection cannot be decreased!

PATCH {{baseUrl}}/odata/v4/spacefarer/GalacticSpacefarers(70416e33-224b-4970-a624-168662918af5)
Authorization: Basic junior@space.com:password
Content-Type: application/json

{
    "stardustCollection": 2
}

### ------------------------------------------------------------------------
# Whormhole navigation skill cannot be decreased!

PATCH {{baseUrl}}/odata/v4/spacefarer/GalacticSpacefarers(70416e33-224b-4970-a624-168662918af5)
Authorization: Basic senior@space.com:password
Content-Type: application/json

{
    "wormholeNavigationSkill": 2
}

### ------------------------------------------------------------------------
# Enhance stardust collection and wormhole navigation skills
POST {{baseUrl}}/odata/v4/spacefarer/GalacticSpacefarers
Authorization: Basic admin@space.com:password
Content-Type: application/json

{
    "name": "Test Spacefarer",
    "email": "test6@spacefarer.com",
    "password": "password",
    "stardustCollection": 1,
    "wormholeNavigationSkill": 1,
    "originPlanet": "Earth",
    "spacesuitColor": "Red",
    "department_ID": "7dacdb28-0601-40f0-8c64-cd86732db1f0",
    "position_ID": "40493cf4-e1af-4ca7-bbc1-941bd80bd97e"
}